# Generated by Django 4.2.6 on 2023-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreloadDataItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='photos/preload/', verbose_name='Фото')),
            ],
        ),
    ]
