# Generated by Django 4.2.6 on 2023-10-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="code",
            field=models.CharField(
                default="", max_length=6, verbose_name="Код авторизации"
            ),
        ),
    ]
