# Generated by Django 4.2.6 on 2023-10-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="code",
            field=models.CharField(
                default="", max_length=6, null=True, verbose_name="Код авторизации"
            ),
        ),
    ]
