# Generated by Django 4.2.6 on 2023-10-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_alter_preloaddataitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
