# Generated by Django 4.2.6 on 2023-10-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_story_alter_customuser_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="img",
        ),
        migrations.CreateModel(
            name="StoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/stories/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.story",
                        verbose_name="История",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотка истории",
                "verbose_name_plural": "Фотки истории",
            },
        ),
    ]
