# Generated by Django 4.2.6 on 2023-10-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_story_img_storyimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyimage",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.story",
                verbose_name="История",
            ),
        ),
    ]
