# Generated by Django 4.2.6 on 2023-10-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_customuser_code"),
        ("api", "0005_alter_storyimage_story"),
    ]

    operations = []
