# Generated by Django 4.2.6 on 2023-10-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_merge_20231022_0331"),
        ("api", "0006_note"),
    ]

    operations = []
