# Generated by Django 4.2.6 on 2023-10-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_merge_0006_merge_20231022_0331_0006_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="categories/icons/",
                verbose_name="Иконка",
            ),
        ),
    ]
