# Generated by Django 4.2.6 on 2023-10-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_expense_type_income_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
    ]
